title: AIGC Acceleration Arxiv Daily
description: Automatically Update AIGC Acceleration Papers Daily using Github Actions (Update Every 12 hours)
show_downloads: true

github:
  zip_url: https://github.com/MathewLi9527/aigc-acceleration-arxiv-daily
  another_url: https://github.com/MathewLi9527/aigc-acceleration-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: MathewLi9527

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
